# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Box selection
  config.vm.box = "ubuntu/precise64"

  # Virtualbox config
  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.name = "Ubuntu 14.04 64-bit"
     vb.memory = 1000
     vb.cpus = 2
  end
 
  # Provision with bootstrap.sh
  config.vm.provision :puppet

end
